#service_name: proxy-parser
apiVersion: v1
kind: Namespace
metadata:
  name: micro
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: proxy-parser
  name: proxy-parser
  namespace: micro
spec:
  selector:
    app: proxy-parser
  ports:
    - name: proxy-parser
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-env
  namespace: micro
#  labels:
#    app: mariadb
data:
  SERVICE_ENV: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-parser
  namespace: micro
  labels:
    app: proxy-parser
data:
  SERVICE_NAME: proxy-parser
  NATS_URL: nats://demo.nats.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-parser
  namespace: micro
  labels:
    app: proxy-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-parser
  template:
    metadata:
      labels:
        app: proxy-parser
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: proxy-parser
          image: aibotsoft/proxy-parser
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: micro-env
            - configMapRef:
                name: proxy-parser
          ports:
            - name: proxy-parser
              containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi